services:
  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pas123
      POSTGRES_DB: UsersDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  studentsforum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studentsforum
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - authservice
    environment:
      - DB_NAME=UsersDB
      - DB_USER=postgres
      - DB_PASSWORD=pas123
      - DB_HOST=db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://authservice:8001
    volumes:
      - .:/app
    env_file:
      - .env

  authservice:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: authservice
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DB_NAME=UsersDB
      - DB_USER=postgres
      - DB_PASSWORD=pas123
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./auth_service:/app
    env_file:
      - ./auth_service/.env

volumes:
  postgres_data:
