services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pas123
      POSTGRES_DB: UsersDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  studentsforum:
    build: .
    container_name: studentsforum
    command: bash -c "python manage.py migrate && daphne student_forum.asgi:application --bind 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app

  authservice:
    build: ./auth_service
    container_name: authservice
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - ./auth_service/.env
    restart: always
    volumes:
      - ./auth_service:/app

volumes:
  postgres_data:
