name: Deploy to Yandex Cloud
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/vm_key
          chmod 600 ~/.ssh/vm_key
          ssh-keyscan ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Execute Deployment
        run: |
          ssh -i ~/.ssh/vm_key daniilyakovlev@${{ secrets.VM_IP }} "
            cd ~/StudentsForum
            git fetch origin
            git reset --hard origin/main
            docker compose down
            docker compose up -d --build
          "